# 主题颜色
color:
  primary: indigo
  accent: pink

header_picture_link: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87489781_p0.webp
avatar: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/Avatar.png
favicon: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/Avatar.png
excerpt_length: 250 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳

# 搜索（还没做呢）
search:
  local: true
  path: /search.xml

# 文章末尾插入的文段，%title%表示文章标题，%link%表示文章链接
passage_end_tag:
  enabled: true
  text: '全文完'

# 抽屉菜单
# 格式: 名称: 链接 || 前缀(图标)
# 图标到这里找 https://www.mdui.org/docs/material_icon
drawer:
  主页: / || &#xe88a;
  友情链接: /friends || &#xe7fb;
  Yuameshi: https://www.yuameshi.top/ || &#xe869;
  MDx: https://github.com/Yuameshi/hexo-theme-mdx || &#xe869;
  关于: /about || &#xe88e;

drawer_about:
  enable: true
  name: Yuameshi
  slogan: qwq
  background: https://cdn.jsdelivr.net/gh/Yuameshi/Blog-CDN@main/background-pictures/87478484_p0.webp
  is_dark: true

footer:
  since: 2022
  copyrights: true
  hexo: true
  theme: true
  text: Hello World!
  contact:
    Github: https://github.com/Yuameshi/ || fa fa-github
    MDx: https://github.com/Yuameshi/hexo-theme-mdx || fa fa-about
  miit_icp: 
  moe_icp: 