# 主题设置
use_cdn: true # 是否使用 CDN 加速（cdn.jsdelivr.net）

# 主题颜色
color:
  primary: indigo
  accent: pink

gdpr_cookie_alert:
  enable: true
  text: 此网站使用Cookie来改善您的体验。

header_picture_link: 
favicon: 
excerpt_length: 250 #自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳  
tag_page_count: true #Tag页是否计数

# 搜索(还没做)
search:
  local: true
  path: /search.xml

# 抽屉菜单的关于
drawer_about:
  enable: true
  avatar: 
  name: 
  slogan: 
  background: 
  is_dark: true

# 抽屉菜单
# 格式: 名称: 链接 || 前缀(图标)
# 图标到找 https://www.mdui.org/docs/material_icon
drawer:
  主页: / || &#xe88a;
  MDx: https://github.com/Yuameshi/hexo-theme-mdx || &#xe243;
  GitHub: https://github.com/Yuameshi || &#xe149;
  关于: /about || &#xe88e;

# 文章末尾插入的文段，%title%表示文章标题，%link%表示文章链接
passage_end_tag:
  enabled: true
  text: '全文完'

comment:
  use: 
  gitalk:
    clientID: 
    clientSecret: 
    repo: 
    owner: 
    admin: ['']
    distractionFreeMode: true
  utteranc:
    repo: 
    issue_term: 
    lable: 
    theme: 


analytics:
  google:
    enabled: false
    tracking_id: 
  cloudflare:
    enabled: false
    token: 

footer:
  since: 
  copyrights: true
  hexo: true
  theme: true
  text: 
  contact:
    MDx: https://github.com/Yuameshi/hexo-theme-mdx
    GitHub: https://github.com/Yuameshi
  miit_icp: 
  moe_icp: 